package com.openggf.audio;

import com.openggf.audio.smps.AbstractSmpsData;
import com.openggf.audio.smps.DacData;
import com.openggf.audio.smps.SmpsSequencer;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import com.openggf.audio.driver.SmpsDriver;
import com.openggf.audio.synth.Ym2612Chip;
import com.openggf.data.Rom;
import com.openggf.game.sonic2.audio.Sonic2SmpsSequencerConfig;
import com.openggf.game.sonic2.audio.smps.Sonic2SmpsLoader;
import static com.openggf.tests.RomTestUtils.ensureRomAvailable;

import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.UnsupportedAudioFileException;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import static org.junit.Assert.*;
import static org.junit.Assume.assumeTrue;

/**
 * Audio regression tests that compare current audio output against pre-generated reference files.
 * This ensures that optimizations do not change the audio output.
 *
 * Reference files are generated by AudioReferenceGenerator and stored in src/test/resources/audio-reference/
 */
public class AudioRegressionTest {

    private static final String REFERENCE_DIR = "audio-reference";
    private static final double SAMPLE_RATE = Ym2612Chip.getDefaultOutputRate();
    private static final int BUFFER_SIZE = 1024;

    // Tolerance for sample comparison (0 = exact match required)
    // Some minor floating point variations may occur, so allow small tolerance
    private static final int SAMPLE_TOLERANCE = 0;

    // Music IDs
    private static final int MUSIC_EHZ = 0x81;
    private static final int MUSIC_CPZ = 0x8C;
    private static final int MUSIC_HTZ = 0x94;

    // SFX IDs
    private static final int SFX_RING = 0xB5;
    private static final int SFX_JUMP = 0xA3;
    private static final int SFX_SPRING = 0xB1;

    private static Rom rom;
    private static Sonic2SmpsLoader loader;
    private static DacData dacData;
    private static boolean referenceFilesExist;

    @BeforeClass
    public static void setUpClass() {
        try {
            File romFile = ensureRomAvailable();
            rom = new Rom();
            assertTrue("Failed to open ROM", rom.open(romFile.getAbsolutePath()));
            loader = new Sonic2SmpsLoader(rom);
            dacData = loader.loadDacData();

            // Check if reference files exist
            referenceFilesExist = referenceFileExists("music_ehz.wav");
        } catch (Exception e) {
            // ROM not available, tests will be skipped
            referenceFilesExist = false;
        }
    }

    @Before
    public void setUp() {
        // Don't assume reference files exist for benchmark test - it's independent
        // Reference file check is done per-test for regression tests
    }

    @Test
    public void testMusicEhzMatchesReference() throws Exception {
        assumeTrue("Reference files not generated yet. Run AudioReferenceGenerator first.", referenceFilesExist);
        assertMusicMatchesReference("music_ehz.wav", MUSIC_EHZ, 10.0);
    }

    @Test
    public void testMusicCpzMatchesReference() throws Exception {
        assumeTrue("Reference files not generated yet. Run AudioReferenceGenerator first.", referenceFilesExist);
        assertMusicMatchesReference("music_cpz.wav", MUSIC_CPZ, 10.0);
    }

    @Test
    public void testMusicHtzMatchesReference() throws Exception {
        assumeTrue("Reference files not generated yet. Run AudioReferenceGenerator first.", referenceFilesExist);
        assertMusicMatchesReference("music_htz.wav", MUSIC_HTZ, 10.0);
    }

    @Test
    public void testSfxRingMatchesReference() throws Exception {
        assumeTrue("Reference files not generated yet. Run AudioReferenceGenerator first.", referenceFilesExist);
        assertSfxMatchesReference("sfx_ring.wav", SFX_RING);
    }

    @Test
    public void testSfxJumpMatchesReference() throws Exception {
        assumeTrue("Reference files not generated yet. Run AudioReferenceGenerator first.", referenceFilesExist);
        assertSfxMatchesReference("sfx_jump.wav", SFX_JUMP);
    }

    @Test
    public void testSfxSpringMatchesReference() throws Exception {
        assumeTrue("Reference files not generated yet. Run AudioReferenceGenerator first.", referenceFilesExist);
        assertSfxMatchesReference("sfx_spring.wav", SFX_SPRING);
    }

    @Test
    public void testMixedMusicSfxMatchesReference() throws Exception {
        assumeTrue("Reference files not generated yet. Run AudioReferenceGenerator first.", referenceFilesExist);
        assumeTrue("Mixed reference file not found", referenceFileExists("mixed_music_sfx.wav"));

        short[] reference = loadReferenceWav("mixed_music_sfx.wav");
        assertNotNull("Reference file should load", reference);

        // Generate current output
        AbstractSmpsData musicData = loader.loadMusic(MUSIC_EHZ);
        AbstractSmpsData sfxRingData = loader.loadSfx(SFX_RING);
        AbstractSmpsData sfxJumpData = loader.loadSfx(SFX_JUMP);

        SmpsDriver driver = new SmpsDriver(SAMPLE_RATE);
        driver.setRegion(SmpsSequencer.Region.NTSC);

        SmpsSequencer musicSeq = new SmpsSequencer(musicData, dacData, driver, Sonic2SmpsSequencerConfig.CONFIG);
        musicSeq.setSampleRate(SAMPLE_RATE);
        driver.addSequencer(musicSeq, false);

        short[] current = new short[reference.length];
        short[] buffer = new short[BUFFER_SIZE * 2];

        int samplesWritten = 0;
        int sfx1TriggerFrame = (int) (0.5 * SAMPLE_RATE);
        int sfx2TriggerFrame = (int) (1.0 * SAMPLE_RATE);
        boolean sfx1Triggered = false;
        boolean sfx2Triggered = false;

        while (samplesWritten < current.length) {
            int currentFrame = samplesWritten / 2;

            if (!sfx1Triggered && currentFrame >= sfx1TriggerFrame && sfxRingData != null) {
                SmpsSequencer sfxSeq = new SmpsSequencer(sfxRingData, dacData, driver, Sonic2SmpsSequencerConfig.CONFIG);
                sfxSeq.setSampleRate(SAMPLE_RATE);
                sfxSeq.setSfxMode(true);
                driver.addSequencer(sfxSeq, true);
                sfx1Triggered = true;
            }

            if (!sfx2Triggered && currentFrame >= sfx2TriggerFrame && sfxJumpData != null) {
                SmpsSequencer sfxSeq = new SmpsSequencer(sfxJumpData, dacData, driver, Sonic2SmpsSequencerConfig.CONFIG);
                sfxSeq.setSampleRate(SAMPLE_RATE);
                sfxSeq.setSfxMode(true);
                driver.addSequencer(sfxSeq, true);
                sfx2Triggered = true;
            }

            int toRead = Math.min(buffer.length, current.length - samplesWritten);
            driver.read(buffer);
            System.arraycopy(buffer, 0, current, samplesWritten, toRead);
            samplesWritten += toRead;
        }

        assertAudioEquals("mixed_music_sfx.wav", reference, current);
    }

    /**
     * Performance benchmark test - measures time to render audio.
     */
    @Test
    public void benchmarkAudioRendering() {
        assumeTrue("ROM not available, skipping benchmark", loader != null);
        AbstractSmpsData musicData = loader.loadMusic(MUSIC_EHZ);
        assertNotNull("Music data should load", musicData);

        SmpsDriver driver = new SmpsDriver(SAMPLE_RATE);
        driver.setRegion(SmpsSequencer.Region.NTSC);

        SmpsSequencer seq = new SmpsSequencer(musicData, dacData, driver, Sonic2SmpsSequencerConfig.CONFIG);
        seq.setSampleRate(SAMPLE_RATE);
        driver.addSequencer(seq, false);

        short[] buffer = new short[BUFFER_SIZE * 2];

        // Warm up
        for (int i = 0; i < 100; i++) {
            driver.read(buffer);
        }

        // Reset for actual benchmark
        driver = new SmpsDriver(SAMPLE_RATE);
        driver.setRegion(SmpsSequencer.Region.NTSC);
        seq = new SmpsSequencer(musicData, dacData, driver, Sonic2SmpsSequencerConfig.CONFIG);
        seq.setSampleRate(SAMPLE_RATE);
        driver.addSequencer(seq, false);

        // Benchmark: render 1 second of audio (SAMPLE_RATE / BUFFER_SIZE iterations)
        int iterations = (int) (SAMPLE_RATE / BUFFER_SIZE);
        long start = System.nanoTime();
        for (int i = 0; i < iterations; i++) {
            driver.read(buffer);
        }
        long elapsed = System.nanoTime() - start;

        double msPerSecond = elapsed / 1_000_000.0;
        System.out.println("Audio render time: " + msPerSecond + " ms per second of audio");
        System.out.println("Real-time factor: " + (1000.0 / msPerSecond) + "x");

        // Assert reasonable performance (should be under 50ms to render 1 second at minimum)
        // On modern hardware this should be <5ms, but we use a lenient threshold
        assertTrue("Audio rendering should complete in reasonable time (under 100ms for 1 second of audio)",
                msPerSecond < 100.0);
    }

    private void assertMusicMatchesReference(String filename, int musicId, double durationSeconds) throws Exception {
        assumeTrue("Reference file not found: " + filename, referenceFileExists(filename));

        short[] reference = loadReferenceWav(filename);
        assertNotNull("Reference file should load: " + filename, reference);

        // Generate current output
        AbstractSmpsData musicData = loader.loadMusic(musicId);
        assertNotNull("Music data should load for ID 0x" + Integer.toHexString(musicId), musicData);

        SmpsDriver driver = new SmpsDriver(SAMPLE_RATE);
        driver.setRegion(SmpsSequencer.Region.NTSC);

        SmpsSequencer seq = new SmpsSequencer(musicData, dacData, driver, Sonic2SmpsSequencerConfig.CONFIG);
        seq.setSampleRate(SAMPLE_RATE);
        driver.addSequencer(seq, false);

        short[] current = renderAudio(driver, reference.length);

        assertAudioEquals(filename, reference, current);
    }

    private void assertSfxMatchesReference(String filename, int sfxId) throws Exception {
        assumeTrue("Reference file not found: " + filename, referenceFileExists(filename));

        short[] reference = loadReferenceWav(filename);
        assertNotNull("Reference file should load: " + filename, reference);

        // Generate current output
        AbstractSmpsData sfxData = loader.loadSfx(sfxId);
        assertNotNull("SFX data should load for ID 0x" + Integer.toHexString(sfxId), sfxData);

        SmpsDriver driver = new SmpsDriver(SAMPLE_RATE);
        driver.setRegion(SmpsSequencer.Region.NTSC);

        SmpsSequencer seq = new SmpsSequencer(sfxData, dacData, driver, Sonic2SmpsSequencerConfig.CONFIG);
        seq.setSampleRate(SAMPLE_RATE);
        seq.setSfxMode(true);
        driver.addSequencer(seq, true);

        short[] current = renderAudio(driver, reference.length);

        assertAudioEquals(filename, reference, current);
    }

    private void assertAudioEquals(String context, short[] reference, short[] current) {
        assertEquals("Sample count mismatch for " + context, reference.length, current.length);

        int maxDeviation = 0;
        long sumSquaredError = 0;
        int firstMismatchIndex = -1;

        for (int i = 0; i < reference.length; i++) {
            int diff = Math.abs(reference[i] - current[i]);
            if (diff > maxDeviation) {
                maxDeviation = diff;
            }
            sumSquaredError += (long) diff * diff;

            if (diff > SAMPLE_TOLERANCE && firstMismatchIndex < 0) {
                firstMismatchIndex = i;
            }
        }

        double rmsError = Math.sqrt((double) sumSquaredError / reference.length);

        if (maxDeviation > SAMPLE_TOLERANCE) {
            int sampleIndex = firstMismatchIndex / 2; // Convert to frame index
            double timeSeconds = sampleIndex / SAMPLE_RATE;
            fail(String.format(
                    "Audio mismatch for %s: max deviation=%d (tolerance=%d), RMS error=%.2f, " +
                    "first mismatch at sample %d (%.3f seconds), ref=%d, current=%d",
                    context, maxDeviation, SAMPLE_TOLERANCE, rmsError,
                    sampleIndex, timeSeconds, reference[firstMismatchIndex], current[firstMismatchIndex]
            ));
        }

        System.out.println(String.format("Audio match verified for %s: max deviation=%d, RMS error=%.2f",
                context, maxDeviation, rmsError));
    }

    private short[] renderAudio(SmpsDriver driver, int totalSamples) {
        short[] audio = new short[totalSamples];
        short[] buffer = new short[BUFFER_SIZE * 2];

        int samplesWritten = 0;
        while (samplesWritten < totalSamples) {
            int toRead = Math.min(buffer.length, totalSamples - samplesWritten);
            driver.read(buffer);
            System.arraycopy(buffer, 0, audio, samplesWritten, toRead);
            samplesWritten += toRead;
        }

        return audio;
    }

    private static boolean referenceFileExists(String filename) {
        try (InputStream is = AudioRegressionTest.class.getClassLoader().getResourceAsStream(REFERENCE_DIR + "/" + filename)) {
            return is != null;
        } catch (IOException e) {
            return false;
        }
    }

    private short[] loadReferenceWav(String filename) throws IOException, UnsupportedAudioFileException {
        // Try loading from classpath first
        try (InputStream is = getClass().getClassLoader().getResourceAsStream(REFERENCE_DIR + "/" + filename)) {
            if (is == null) {
                // Fall back to file system
                Path filePath = Paths.get("src/test/resources", REFERENCE_DIR, filename);
                if (!Files.exists(filePath)) {
                    return null;
                }
                return loadWavFromFile(filePath.toFile());
            }

            // Copy to temp file for AudioSystem (doesn't support streams well)
            File tempFile = File.createTempFile("audio_ref_", ".wav");
            tempFile.deleteOnExit();
            Files.copy(is, tempFile.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
            return loadWavFromFile(tempFile);
        }
    }

    private short[] loadWavFromFile(File file) throws IOException, UnsupportedAudioFileException {
        try (AudioInputStream ais = AudioSystem.getAudioInputStream(file)) {
            AudioFormat format = ais.getFormat();

            // Verify format matches what we expect
            assertEquals("Sample rate mismatch", (float) SAMPLE_RATE, format.getSampleRate(), 0.1f);
            assertEquals("Channels mismatch", 2, format.getChannels());
            assertEquals("Sample size mismatch", 16, format.getSampleSizeInBits());

            byte[] bytes = ais.readAllBytes();
            short[] samples = new short[bytes.length / 2];

            // Convert little-endian bytes to shorts
            for (int i = 0; i < samples.length; i++) {
                int lo = bytes[i * 2] & 0xFF;
                int hi = bytes[i * 2 + 1];
                samples[i] = (short) ((hi << 8) | lo);
            }

            return samples;
        }
    }
}
