package com.openggf.game.rewind.snapshot;

import java.util.Map;

/**
 * Snapshot of {@link com.openggf.game.animation.AnimatedTileChannelGraph} per-frame state.
 * Captures the last-resolved phase per channel so rewind round-trips animated
 * tile animation state. The channels list itself is set at zone load and treated
 * as immutable for rewind; pattern bytes are derived state regenerated by the
 * animator counters (Track E) and are excluded.
 */
public record AnimatedTileChannelSnapshot(Map<String, Integer> lastPhaseByChannel) {
    public AnimatedTileChannelSnapshot {
        lastPhaseByChannel = Map.copyOf(lastPhaseByChannel);
    }
}
